### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [erwilkinson/prj-rev-bwfs-dasmoto#2]
Overall, your work almost met the project specifications. Other than the images not loading, everything was perfect. I loved the commenting and spacing in your HTML file -- be sure to keep that up. Next time, just be more mindful of your file paths.

Good luck! :)

**Comment by erwilkinson** [comment]
Thanks! Yeah I was having trouble between absolute and relative paths so it was easier to just use the full project path. I will do some further study on paths so that I can use them better! :)
